# Generated by Django 5.0.6 on 2024-08-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espoir_collectif', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='don',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
