# Generated by Django 5.0.6 on 2024-08-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espoir_collectif', '0002_don_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='don',
            name='message',
        ),
        migrations.RemoveField(
            model_name='donateur',
            name='prenom',
        ),
        migrations.AddField(
            model_name='donateur',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='donateur',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
